/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.hyruleevents.fronted;

import com.mycompany.hyruleevents.backend.ArchivoNullException;
import com.mycompany.hyruleevents.backend.CarpetaSalidaNullException;
import com.mycompany.hyruleevents.backend.GestorDeArchivos;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.DIRECTORIES_ONLY;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author edu
 */
public class CargaDeArchivoPanel extends javax.swing.JPanel {

    private GestorDeArchivos gestorDeArchivos;

    public CargaDeArchivoPanel(GestorDeArchivos gestorDeArchivos) {
        initComponents();
        this.gestorDeArchivos = gestorDeArchivos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        SiguenteBtn = new javax.swing.JButton();
        ElegirSalidaBtn = new javax.swing.JButton();
        CargarBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        VelocidadTf = new javax.swing.JTextField();

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel2.setText("Velocidad de procesamiento (en ms):");

        SiguenteBtn.setText("Siguente");
        SiguenteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguenteBtnActionPerformed(evt);
            }
        });

        ElegirSalidaBtn.setText("Elegir salida");
        ElegirSalidaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElegirSalidaBtnActionPerformed(evt);
            }
        });

        CargarBtn.setText("Cargar Archivo");
        CargarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setText("A continuación cargue el archivo de texto y elija el path de salida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(SiguenteBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VelocidadTf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CargarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(ElegirSalidaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(38, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(9, 9, 9)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CargarBtn)
                    .addComponent(ElegirSalidaBtn))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(VelocidadTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(SiguenteBtn)
                .addGap(40, 40, 40))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(239, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SiguenteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguenteBtnActionPerformed

        try {
            gestorDeArchivos.validarArchivoDeTexto();
            gestorDeArchivos.validarCarpetaDeSalida();
            int velocidad = Integer.valueOf(this.VelocidadTf.getText());
            gestorDeArchivos.setVelocidadDeProcesamiento(velocidad);
            System.out.println("todo está bien, siguente");

        } catch (ArchivoNullException e) {
            JOptionPane.showMessageDialog(CargarBtn, "Elija el archivo de entrada");
        } catch (CarpetaSalidaNullException e) {
            JOptionPane.showMessageDialog(CargarBtn, "Elija el directorio de salida");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(CargarBtn, "La velocidad debe ser un numero entero (ms)");
        }

    }//GEN-LAST:event_SiguenteBtnActionPerformed

    private void ElegirSalidaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElegirSalidaBtnActionPerformed
        JFileChooser fc = new JFileChooser();

        fc.setFileSelectionMode(DIRECTORIES_ONLY);
        int eleccion = fc.showOpenDialog(this);
        if (eleccion == JFileChooser.APPROVE_OPTION) {
            this.gestorDeArchivos.setCarpetaSalida(fc.getSelectedFile());
            System.out.println(fc.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_ElegirSalidaBtnActionPerformed

    private void CargarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarBtnActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter filtroTexto = new FileNameExtensionFilter("Archivos de texto", "txt");
        fc.setFileFilter(filtroTexto);
        int eleccion = fc.showOpenDialog(this);

        if (eleccion == JFileChooser.APPROVE_OPTION) {
            this.gestorDeArchivos.setArchivoDeTexto(fc.getSelectedFile());
        }
    }//GEN-LAST:event_CargarBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarBtn;
    private javax.swing.JButton ElegirSalidaBtn;
    private javax.swing.JButton SiguenteBtn;
    private javax.swing.JTextField VelocidadTf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
