/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hyruleevents.fronted.consultas;

import com.mycompany.hyruleevents.backend.EjecutadorDeInstruccionesFrontend;
import java.awt.BorderLayout;

/**
 *
 * @author edu
 */
public class ConsultasFrame extends javax.swing.JFrame {

    private EjecutadorDeInstruccionesFrontend ejecutador;
    /**
     * Creates new form NewJFrame
     */
    public ConsultasFrame(EjecutadorDeInstruccionesFrontend ejecutador) {
        initComponents();
        this.desktopPane.setLayout(new BorderLayout());
        this.ejecutador = ejecutador;
    }

    
    public void limpiarDesktopPane(){
        this.desktopPane.removeAll();
        this.desktopPane.revalidate();
        this.desktopPane.repaint();
    }
    
    
    private void refrescarTodo(){
        this.desktopPane.revalidate();
        this.desktopPane.repaint();
        this.revalidate();
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        cosas = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        inscripcion = new javax.swing.JMenu();
        pago = new javax.swing.JMenu();
        validarInscripcion = new javax.swing.JMenu();
        actividad = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(153, 173, 185));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        cosas.setText("Evento");
        cosas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cosasMouseClicked(evt);
            }
        });
        cosas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosasActionPerformed(evt);
            }
        });
        jMenuBar2.add(cosas);

        jMenu4.setBackground(new java.awt.Color(246, 176, 91));
        jMenu4.setText("Participante");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu4);

        inscripcion.setText("Inscripcion");
        inscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inscripcionMouseClicked(evt);
            }
        });
        jMenuBar2.add(inscripcion);

        pago.setText("Pago");
        pago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pagoMouseClicked(evt);
            }
        });
        jMenuBar2.add(pago);

        validarInscripcion.setText("Validar inscripcion");
        validarInscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                validarInscripcionMouseClicked(evt);
            }
        });
        jMenuBar2.add(validarInscripcion);

        actividad.setText("Actividad");
        actividad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actividadMouseClicked(evt);
            }
        });
        jMenuBar2.add(actividad);

        jMenu9.setText("jMenu9");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("jMenu10");
        jMenuBar2.add(jMenu10);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cosasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosasActionPerformed
       
    }//GEN-LAST:event_cosasActionPerformed

    private void cosasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cosasMouseClicked
        this.desktopPane.removeAll();
        RegistroEventoFrame registro = new RegistroEventoFrame(ejecutador, this);
        registro.setVisible(true);
        this.desktopPane.add(registro, BorderLayout.CENTER);
        this.refrescarTodo();
    }//GEN-LAST:event_cosasMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
       this.desktopPane.removeAll();
        RegistroParticipanteFrame registro = new RegistroParticipanteFrame(ejecutador, this);
        registro.setVisible(true);
        this.desktopPane.add(registro, BorderLayout.CENTER);
        this.refrescarTodo();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void inscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inscripcionMouseClicked
        this.desktopPane.removeAll();
        RegistroInscripcion registro = new RegistroInscripcion(ejecutador, this);
        registro.setVisible(true);
        this.desktopPane.add(registro, BorderLayout.CENTER);
        this.refrescarTodo();
    }//GEN-LAST:event_inscripcionMouseClicked

    private void pagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pagoMouseClicked
         this.desktopPane.removeAll();
        PagoFrame registro = new PagoFrame(ejecutador, this);
        registro.setVisible(true);
        this.desktopPane.add(registro, BorderLayout.CENTER);
        this.refrescarTodo();
    }//GEN-LAST:event_pagoMouseClicked

    private void validarInscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_validarInscripcionMouseClicked
        this.desktopPane.removeAll();
        ValidarInscripcionFrame registro = new ValidarInscripcionFrame(ejecutador, this);
        registro.setVisible(true);
        this.desktopPane.add(registro, BorderLayout.CENTER);
        this.refrescarTodo();
    }//GEN-LAST:event_validarInscripcionMouseClicked

    private void actividadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actividadMouseClicked
        this.desktopPane.removeAll();
        RegistroActividad registro = new RegistroActividad(ejecutador, this);
        registro.setVisible(true);
        this.desktopPane.add(registro, BorderLayout.CENTER);
        this.refrescarTodo();
    }//GEN-LAST:event_actividadMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu actividad;
    private javax.swing.JMenu cosas;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu inscripcion;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu pago;
    private javax.swing.JMenu validarInscripcion;
    // End of variables declaration//GEN-END:variables
}
