/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hyruleevents.fronted.consultas;

import com.mycompany.hyruleevents.backend.EjecutadorDeInstruccionesFrontend;
import java.awt.BorderLayout;

/**
 *
 * @author edu
 */
public class ConsultasFrame extends javax.swing.JFrame {

    private EjecutadorDeInstruccionesFrontend ejecutador;
    /**
     * Creates new form NewJFrame
     */
    public ConsultasFrame(EjecutadorDeInstruccionesFrontend ejecutador) {
        initComponents();
        this.desktopPane.setLayout(new BorderLayout());
        this.ejecutador = ejecutador;
    }

    
    public void limpiarDesktopPane(){
        this.desktopPane.removeAll();
        this.desktopPane.revalidate();
        this.desktopPane.repaint();
    }
    
    
    private void refrescarTodo(){
        this.desktopPane.revalidate();
        this.desktopPane.repaint();
        this.revalidate();
        this.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        cosas = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(153, 173, 185));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        cosas.setText("Evento");
        cosas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cosasMouseClicked(evt);
            }
        });
        cosas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosasActionPerformed(evt);
            }
        });
        jMenuBar2.add(cosas);

        jMenu4.setBackground(new java.awt.Color(246, 176, 91));
        jMenu4.setText("Participante");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu4);

        jMenu5.setText("jMenu5");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("jMenu6");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("jMenu7");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("jMenu8");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("jMenu9");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("jMenu10");
        jMenuBar2.add(jMenu10);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cosasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosasActionPerformed
       
    }//GEN-LAST:event_cosasActionPerformed

    private void cosasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cosasMouseClicked
        this.desktopPane.removeAll();
        RegistroEventoFrame registro = new RegistroEventoFrame(ejecutador, this);
        registro.setVisible(true);
        this.desktopPane.add(registro, BorderLayout.CENTER);
        this.refrescarTodo();
    }//GEN-LAST:event_cosasMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
       this.desktopPane.removeAll();
        RegistroParticipanteFrame registro = new RegistroParticipanteFrame(ejecutador, this);
        registro.setVisible(true);
        this.desktopPane.add(registro, BorderLayout.CENTER);
        this.refrescarTodo();
    }//GEN-LAST:event_jMenu4MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu cosas;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
