/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.hyruleevents.fronted.consultas;

import com.mycompany.hyruleevents.backend.EjecutadorDeInstruccionesFrontend;
import com.mycompany.hyruleevents.backend.instruciones.InstruccionException;
import com.mycompany.hyruleevents.backend.verificacionesDB.ExceptionEnDB;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author edu
 */
public class RegistroActividad extends javax.swing.JInternalFrame {

     private EjecutadorDeInstruccionesFrontend ejecutador;
     private ConsultasFrame framePadre;
    /**
     * Creates new form NewJInternalFrame
     */
    public RegistroActividad(EjecutadorDeInstruccionesFrontend ejecutador, ConsultasFrame framePadre) {
        initComponents();
        this.ejecutador = ejecutador;
        this.framePadre = framePadre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipoActividadCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        horaInicioL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        correoEncargadoL = new javax.swing.JTextField();
        btnContinuar = new javax.swing.JButton();
        codigoACtividadL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        codigoEventoL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cupoMaximoL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tituloActividadL = new javax.swing.JTextField();
        horaFinL = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(225, 218, 193));
        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("Registro Actividad");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("Codigo actividad:");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("Tipo actividad:");

        tipoActividadCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHARLA", "TALLER", "DEBATE", "OTRA" }));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel5.setText("Correo del encargado:");

        horaInicioL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaInicioLActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setText("Hora inicio:");

        correoEncargadoL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoEncargadoLActionPerformed(evt);
            }
        });

        btnContinuar.setBackground(new java.awt.Color(204, 204, 204));
        btnContinuar.setText("Continuar");
        btnContinuar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        codigoACtividadL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoACtividadLActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel8.setText("Codigo evento:");

        codigoEventoL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoEventoLActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel7.setText("Hora fin:");

        cupoMaximoL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupoMaximoLActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel9.setText("Cupo maximo:");

        tituloActividadL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloActividadLActionPerformed(evt);
            }
        });

        horaFinL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaFinLActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel10.setText("Titulo actividad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tipoActividadCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaInicioL)
                    .addComponent(correoEncargadoL)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigoACtividadL)
                    .addComponent(codigoEventoL)
                    .addComponent(cupoMaximoL)
                    .addComponent(tituloActividadL)
                    .addComponent(horaFinL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoACtividadL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(codigoEventoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipoActividadCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloActividadL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoEncargadoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horaInicioL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(horaFinL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cupoMaximoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnContinuar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void horaInicioLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaInicioLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaInicioLActionPerformed

    private void correoEncargadoLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoEncargadoLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoEncargadoLActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        String codigoActividad = this.codigoACtividadL.getText();
        String codigoEvento = this.codigoEventoL.getText();
        String tipoActividad = this.tipoActividadCombo.getSelectedItem().toString();
        String titulActividad = this.tituloActividadL.getText();
        String correoEncargado = this.correoEncargadoL.getText();
        String horaInicio = this.horaInicioL.getText();
        String horaFin = this.horaFinL.getText();
        String cupoMaximo = this.cupoMaximoL.getText();
        
        String [] parametros = {codigoActividad,codigoEvento,tipoActividad,titulActividad,correoEncargado,horaInicio,horaFin, cupoMaximo};
        boolean todoBien = true;
         try {
             this.ejecutador.registrarActividad(parametros);
         } catch (InstruccionException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
             todoBien = false;
         } catch (ExceptionEnDB ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
             todoBien = false;
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
             todoBien = false;
         }
         
         if(todoBien){
             JOptionPane.showMessageDialog(this, "Query ejecutada exitosamente");
             framePadre.limpiarDesktopPane();
         }
         System.out.println("saliendo del esta cosa");
             
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void codigoACtividadLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoACtividadLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoACtividadLActionPerformed

    private void codigoEventoLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoEventoLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoEventoLActionPerformed

    private void cupoMaximoLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupoMaximoLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cupoMaximoLActionPerformed

    private void tituloActividadLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloActividadLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloActividadLActionPerformed

    private void horaFinLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaFinLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horaFinLActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JTextField codigoACtividadL;
    private javax.swing.JTextField codigoEventoL;
    private javax.swing.JTextField correoEncargadoL;
    private javax.swing.JTextField cupoMaximoL;
    private javax.swing.JTextField horaFinL;
    private javax.swing.JTextField horaInicioL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JComboBox<String> tipoActividadCombo;
    private javax.swing.JTextField tituloActividadL;
    // End of variables declaration//GEN-END:variables
}
