/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.hyruleevents.fronted.consultas;

import com.mycompany.hyruleevents.backend.EjecutadorDeInstruccionesFrontend;
import com.mycompany.hyruleevents.backend.instruciones.InstruccionException;
import com.mycompany.hyruleevents.backend.verificacionesDB.ExceptionEnDB;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author edu
 */
public class RegistroEventoFrame extends javax.swing.JInternalFrame {

     private EjecutadorDeInstruccionesFrontend ejecutador;
     private ConsultasFrame framePadre;
    /**
     * Creates new form NewJInternalFrame
     */
    public RegistroEventoFrame(EjecutadorDeInstruccionesFrontend ejecutador, ConsultasFrame framePadre) {
        initComponents();
        this.ejecutador = ejecutador;
        this.framePadre = framePadre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tituloLbl = new javax.swing.JTextField();
        fechaL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tipoCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cupoMaximoL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ubiacionL = new javax.swing.JTextField();
        btnContinuar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        codigoLbl = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        costoLbl = new javax.swing.JTextField();

        setBackground(new java.awt.Color(225, 218, 193));
        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("Registro evento");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("Codigo: ");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Fecha :");

        fechaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaLActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("Tipo:");

        tipoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHARLA", "CONGRESO", "TALLER", "DEBATE" }));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel5.setText("Ubicacion");

        cupoMaximoL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupoMaximoLActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setText("Cupo maximo:");

        ubiacionL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubiacionLActionPerformed(evt);
            }
        });

        btnContinuar.setBackground(new java.awt.Color(204, 204, 204));
        btnContinuar.setText("Continuar");
        btnContinuar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel7.setText("Titulo");

        codigoLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoLblActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel8.setText("Costo");

        costoLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoLblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fechaL)
                    .addComponent(tituloLbl)
                    .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cupoMaximoL)
                    .addComponent(ubiacionL)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigoLbl)
                    .addComponent(costoLbl))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(costoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubiacionL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cupoMaximoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnContinuar)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fechaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaLActionPerformed

    private void cupoMaximoLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupoMaximoLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cupoMaximoLActionPerformed

    private void ubiacionLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubiacionLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubiacionLActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        String codigo =  this.codigoLbl.getText();
        String fecha = this.fechaL.getText() ;
        String tipo = this.tipoCombo.getSelectedItem().toString();
        String titulo = this.tituloLbl.getText() ;
        String ubicacion = this.ubiacionL.getText() ;
        String cupoMaximo = this.cupoMaximoL.getText();
        String costo = this.costoLbl.getText();
        
        String [] parametros = {codigo,fecha,tipo,titulo,ubicacion,cupoMaximo,costo};
        boolean todoBien = true;
         try {
             this.ejecutador.registrarEvento(parametros);
         } catch (InstruccionException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
             todoBien = false;
         } catch (ExceptionEnDB ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
             todoBien = false;
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
             todoBien = false;
         }
         
         if(todoBien){
             JOptionPane.showMessageDialog(this, "Query ejecutada exitosamente");
             framePadre.limpiarDesktopPane();
         }
         System.out.println("saliendo del esta cosa");
             
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void codigoLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoLblActionPerformed

    private void costoLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoLblActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JTextField codigoLbl;
    private javax.swing.JTextField costoLbl;
    private javax.swing.JTextField cupoMaximoL;
    private javax.swing.JTextField fechaL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> tipoCombo;
    private javax.swing.JTextField tituloLbl;
    private javax.swing.JTextField ubiacionL;
    // End of variables declaration//GEN-END:variables
}
