/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.hyruleevents.fronted.consultas;

import com.mycompany.hyruleevents.backend.EjecutadorDeInstruccionesFrontend;
import com.mycompany.hyruleevents.backend.instruciones.InstruccionException;
import com.mycompany.hyruleevents.backend.verificacionesDB.ExceptionEnDB;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author edu
 */
public class ReporteActividadesF extends javax.swing.JInternalFrame {

     private EjecutadorDeInstruccionesFrontend ejecutador;
     private ConsultasFrame framePadre;
    /**
     * Creates new form NewJInternalFrame
     */
    public ReporteActividadesF(EjecutadorDeInstruccionesFrontend ejecutador, ConsultasFrame framePadre) {
        initComponents();
        this.ejecutador = ejecutador;
        this.framePadre = framePadre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        correoEncargadoL = new javax.swing.JTextField();
        btnContinuar = new javax.swing.JButton();
        codigoEventoL = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tipoActividadL = new javax.swing.JTextField();

        setBackground(new java.awt.Color(225, 218, 193));
        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setText("Reporte Actividades");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("Codigo del evento:");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel5.setText("Correo del encargado:");

        correoEncargadoL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoEncargadoLActionPerformed(evt);
            }
        });

        btnContinuar.setBackground(new java.awt.Color(204, 204, 204));
        btnContinuar.setText("Continuar");
        btnContinuar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });

        codigoEventoL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoEventoLActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel8.setText("Tipo de actividad:");

        tipoActividadL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActividadLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(correoEncargadoL)
                    .addComponent(btnContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigoEventoL)
                    .addComponent(tipoActividadL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(codigoEventoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(tipoActividadL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(correoEncargadoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(58, 58, 58)
                .addComponent(btnContinuar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void correoEncargadoLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoEncargadoLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoEncargadoLActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
        String codigoEvento = this.codigoEventoL.getText();
        String tipoActividad = this.tipoActividadL.getText();
        String corrreoEncargado = this.correoEncargadoL.getText();
        
        String [] parametros = {codigoEvento,tipoActividad,corrreoEncargado};
        boolean todoBien = true;
         try {
             this.ejecutador.generarReporteActividades(parametros);
         } catch (InstruccionException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
             todoBien = false;
         } catch (ExceptionEnDB ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
             todoBien = false;
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, ex.getMessage());
             todoBien = false;
         }
         
         if(todoBien){
             JOptionPane.showMessageDialog(this, "Query ejecutada exitosamente");
             framePadre.limpiarDesktopPane();
         }
         System.out.println("saliendo del esta cosa");
             
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void codigoEventoLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoEventoLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoEventoLActionPerformed

    private void tipoActividadLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActividadLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActividadLActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JTextField codigoEventoL;
    private javax.swing.JTextField correoEncargadoL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField tipoActividadL;
    // End of variables declaration//GEN-END:variables
}
